### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by micah-jaffe** [micah-jaffe/caesarnote#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
- Change fixed sizing
- Get background image to show
- fix error rendering
- add favicon

**Comment by micah-jaffe** [comment]
Changes made :+1:

**Comment by ryan-mapa** [comment]
Nice job!
