### ISSUE TITLE
PA Review: Notes MVP

### ISSUE THREAD

**Issue by micah-jaffe** [micah-jaffe/caesarnote#4]
I finished most of the Notes MVP over the weekend. The rich text editor is still a bit buggy but since that's technically a separate MVP I figured I would put this one up for review. Notebooks and notes go hand in hand so they can probably be reviewed together.

- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
  - [x] User can create new notes from notebook show page
  - [x] User can create a new note in default notebook from All Notes page
  - [x] User can view all notes in given notebook on notebook show page
  - [x] User can view all notes on All Notes page
  - [x] User can update notes by changing the title or body - notes will autosave
- [x] Styling
- [x] Smooth, bug-free navigation
  - [x] User can navigate between All Notes and Notebooks via sidebar
  - [x] Modals and dropdowns display appropriately and lead to correct places
- [x] Adequate and appropriate seeds

**Comment by ryan-mapa** [comment]
Nice! I entered my email for information about those premium features!
